import behind8 from "../Images/behind-8.png";
import React from "react";
import Commonbtn from "./Commonbtn";
export const metadata = {
  title: "Home page",
  description: "Generated by create next app",
};
const Mainsection = () => {
  const data = [
    {
      img: behind8,
      id: 1,
      name: "Designer",
      city: "Hisar",
    },
    {
      img: behind8,
      id: 2,
      name: "Developer",
      city: "Hisar",
    },
    {
      img: behind8,
      id: 3,
      name: "Designer",
      city: "Hisar",
    },
  ];
  return (
    <div>
      <div className="d-flex flex-column align-items-center justify-content-center pb-5">
        <a
          href="/About"
          className="show text-black text-decoration-none p-3 mt-5"
        >
          show about -
        </a>

        <div className="d-flex gap-4">
          {data.map((obj, i) => (
            <div key={i} className=" p-3 crd rounded-lg bg-black  mt-5">
              <img className="w-100" src={obj.img} alt="img" />
              <div className=" d-flex align-items-center justify-content-center gap-3">
                <p className=" text-white head">{obj.id}</p>
                <p className=" text-white head">{obj.name}</p>
              </div>
              <p className=" text-white text-center head">{obj.city}</p>
            </div>
          ))}
        </div>
        <Commonbtn text="view" />
      </div>
    </div>
  );
};

export default Mainsection;
